# Generated by Django 5.1.1 on 2024-10-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discountedproduct",
            name="has_discount_ended",
            field=models.BooleanField(default=False),
        ),
    ]
