# Generated by Django 5.1.1 on 2024-10-02 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_discountedproduct_has_discount_ended"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("add", "Add"), ("sell", "Sell")], max_length=4
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_transaction_logs",
                        to="shop.product",
                    ),
                ),
            ],
        ),
    ]
