# Generated by Django 5.1.1 on 2024-10-02 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_transactionlog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transactionlog",
            options={
                "verbose_name": "Transaction Log",
                "verbose_name_plural": "Transaction Logs",
            },
        ),
    ]
