# Generated by Django 5.1.1 on 2024-10-03 07:35

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_alter_transactionlog_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionlog",
            name="transactionLogId",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="ABCDEF0123456789",
                length=10,
                max_length=21,
                prefix="tlog",
                unique=True,
            ),
        ),
    ]
