# Generated by Django 5.1.1 on 2024-10-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_transactionlog_transactionlogid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moreproductimage",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="mpi_directory_path"
            ),
        ),
        migrations.AlterField(
            model_name="moreproductvideo",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="mpv_directory_path"
            ),
        ),
    ]
