# Generated by Django 5.1.1 on 2024-10-04 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_alter_moreproductimage_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moreproductvideo",
            name="description",
            field=models.TextField(
                blank=True,
                default="This is an additional demo video for the product",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="moreproductvideo",
            name="video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_on_the_additional_video",
                to="shop.productvideo",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_on_the_video",
                to="shop.productvideo",
            ),
        ),
    ]
