# Generated by Django 5.1.1 on 2024-10-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_alter_moreproductvideo_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moreproductvideo",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="mpv_directory_path"
            ),
        ),
    ]
