# Generated by Django 5.1.1 on 2024-10-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_alter_moreproductvideo_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="category_directory_path"
            ),
        ),
    ]
