# Generated by Django 5.1.1 on 2024-10-13 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_alter_category_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="digital",
        ),
        migrations.RemoveField(
            model_name="product",
            name="featured",
        ),
        migrations.RemoveField(
            model_name="product",
            name="in_stock",
        ),
        migrations.RemoveField(
            model_name="product",
            name="product_status",
        ),
        migrations.RemoveField(
            model_name="product",
            name="status",
        ),
        migrations.RemoveField(
            model_name="shop",
            name="authentic_rating",
        ),
        migrations.RemoveField(
            model_name="shop",
            name="chat_resp_time",
        ),
        migrations.RemoveField(
            model_name="shop",
            name="days_return",
        ),
        migrations.RemoveField(
            model_name="shop",
            name="shipping_on_time",
        ),
        migrations.RemoveField(
            model_name="shop",
            name="warranty_period",
        ),
    ]
