# Generated by Django 5.1.1 on 2024-10-15 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_remove_product_digital_remove_product_featured_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="life",
        ),
    ]
