# Generated by Django 5.1.1 on 2024-10-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_remove_product_life"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="discountedproduct",
            name="new_price",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="moreproductvideo",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="product_directory_path"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_quantity",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="productvideo",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shop",
            name="address",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="shop",
            name="contact",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="shop",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="shop",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
