# Generated by Django 5.1.1 on 2024-10-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0004_alter_notification_notificationid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_directory_path"
            ),
        ),
    ]
